"""empty message

Revision ID: 2bd80bec5bd5
Revises: db5112a03594
Create Date: 2020-10-11 20:30:29.381047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd80bec5bd5'
down_revision = 'db5112a03594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('body', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'body')
    # ### end Alembic commands ###
